# Split, Apply, Combine (combine is automatic)
https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html

https://www.youtube.com/watch?v=Wb2Tp35dZ-I

In [47]:
import pandas as pd

In [48]:
# df = pd.read_csv('computerSales.csv')
# ! pip install kagglehub
import kagglehub

# Download latest version
path = kagglehub.dataset_download("landlord/icecreamsales")

print("Path to dataset files:", path)
df = pd.read_csv(path+"/ComputerSales.csv")
# display(df)
df.head()

Path to dataset files: /Users/wenyi/.cache/kagglehub/datasets/landlord/icecreamsales/versions/4

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
0,1,Paul Thomas,M,43,OH,M01-F0024,Desktop,479.99,143.39,Website,January,2018
1,2,Margo Simms,F,37,WV,GT13-0024,Desktop,1249.99,230.89,Flyer 4,January,2018
2,3,Sam Stine,M,26,PA,I3670,Desktop,649.99,118.64,Website,February,2018
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018
4,5,Jessica Elk,F,55,PA,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018

## Split: Groupby

### Groupby by column values

In [49]:
df_grouped = df.groupby('State')
df_grouped

#### Basic information of the groupby result: check groupby attributes, and functions
https://pandas.pydata.org/pandas-docs/stable/reference/groupby.html

#### use len() to get the number of groups

In [50]:
#------------------------------------------------
# how many groups?
print(df_grouped)
print(len(df_grouped))
# check groups
print(df_grouped.groups)

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x115aab010>
4
{'NY': [17, 19, 24, 34, 35], 'OH': [0, 6, 7, 8, 11, 14, 16, 22, 26, 31, 33], 'PA': [2, 3, 4, 5, 10, 12, 13, 15, 18, 20, 21, 25, 27, 28, 30, 32, 36, 37, 38], 'WV': [1, 9, 23, 29]}

In [51]:
# selecting group
display(df_grouped.get_group('PA'))

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
2,3,Sam Stine,M,26,PA,I3670,Desktop,649.99,118.64,Website,February,2018
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018
4,5,Jessica Elk,F,55,PA,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018
5,6,Sally Struthers,F,45,PA,GT13-0024,Desktop,1249.99,230.89,Flyer 2,April,2018
10,11,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 3,November,2018
12,13,Jason Case,M,57,PA,81TC00,Laptop,649.99,122.34,Email,November,2018
13,14,Doug Johnson,M,51,PA,I3670,Desktop,649.99,118.64,Website,December,2018
15,16,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,January,2019
18,19,Mick Roberts,M,23,PA,I3593,Laptop,399.99,72.09,Flyer 4,March,2019
20,21,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,May,2019
21,22,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,August,2019
25,26,Mick Roberts,M,23,PA,Q526FA,Laptop,1049.99,143.09,Email,November,2019
27,28,Moe Eggert,M,35,PA,15M-ED,Laptop,699.99,98.09,Email,December,2019
28,29,Jessica Elk,F,55,PA,GA401IV,Laptop,1349.99,180.34,Flyer 2,December,2019
30,31,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 1,January,2020
32,33,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,March,2020
36,37,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,April,2020
37,38,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,May,2020
38,39,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,May,2020

In [52]:
# iterate through groups
def display_all_groups(df_grouped):
    for key, group in df_grouped:
        print('key: ', key)
        print('group: ')
        display(group)
        
display_all_groups(df_grouped)

key:  NY
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
17,18,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,March,2019
19,20,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2019
24,25,Michelle Samms,F,46,NY,I3670,Desktop,649.99,118.64,Flyer 2,November,2019
34,35,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,April,2020
35,36,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2020

key:  OH
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
0,1,Paul Thomas,M,43,OH,M01-F0024,Desktop,479.99,143.39,Website,January,2018
6,7,Michelle Samms,F,46,OH,GA401IV,Laptop,1349.99,180.34,Email,May,2018
7,8,Mick Roberts,M,23,OH,MY2J2LL,Tablet,999.99,146.69,Website,July,2018
8,9,Ed Klondike,M,52,OH,81TC00,Laptop,649.99,122.34,Email,July,2018
11,12,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,November,2018
14,15,Andy Sands,M,56,OH,MY2J2LL,Tablet,999.99,146.69,Flyer 1,December,2018
16,17,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,February,2019
22,23,Paul Thomas,M,43,OH,81TC00,Laptop,649.99,122.34,Website,August,2019
26,27,Ed Klondike,M,52,OH,Q526FA,Laptop,1049.99,143.09,Website,December,2019
31,32,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,February,2020
33,34,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,March,2020

key:  PA
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
2,3,Sam Stine,M,26,PA,I3670,Desktop,649.99,118.64,Website,February,2018
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018
4,5,Jessica Elk,F,55,PA,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018
5,6,Sally Struthers,F,45,PA,GT13-0024,Desktop,1249.99,230.89,Flyer 2,April,2018
10,11,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 3,November,2018
12,13,Jason Case,M,57,PA,81TC00,Laptop,649.99,122.34,Email,November,2018
13,14,Doug Johnson,M,51,PA,I3670,Desktop,649.99,118.64,Website,December,2018
15,16,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,January,2019
18,19,Mick Roberts,M,23,PA,I3593,Laptop,399.99,72.09,Flyer 4,March,2019
20,21,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,May,2019
21,22,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,August,2019
25,26,Mick Roberts,M,23,PA,Q526FA,Laptop,1049.99,143.09,Email,November,2019
27,28,Moe Eggert,M,35,PA,15M-ED,Laptop,699.99,98.09,Email,December,2019
28,29,Jessica Elk,F,55,PA,GA401IV,Laptop,1349.99,180.34,Flyer 2,December,2019
30,31,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 1,January,2020
32,33,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,March,2020
36,37,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,April,2020
37,38,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,May,2020
38,39,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,May,2020

key:  WV
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
1,2,Margo Simms,F,37,WV,GT13-0024,Desktop,1249.99,230.89,Flyer 4,January,2018
9,10,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,August,2018
23,24,Margo Simms,F,37,WV,Q526FA,Laptop,1049.99,143.09,Flyer 4,November,2019
29,30,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,January,2020

In [53]:
print(df_grouped["Age"])
display_all_groups(df_grouped['Age'])

<pandas.core.groupby.generic.SeriesGroupBy object at 0x115aaae90>
key:  NY
group:

17    46
19    45
24    46
34    46
35    45
Name: Age, dtype: int64

key:  OH
group:

0     43
6     46
7     23
8     52
11    54
14    56
16    46
22    43
26    52
31    54
33    46
Name: Age, dtype: int64

key:  PA
group:

2     26
3     35
4     55
5     45
10    49
12    57
13    51
15    49
18    23
20    57
21    51
25    23
27    35
28    55
30    49
32    49
36    57
37    51
38    35
Name: Age, dtype: int64

key:  WV
group:

1     37
9     56
23    37
29    56
Name: Age, dtype: int64

### Group by multiple column values

In [54]:
df_grouped = df.groupby(by=['State', 'Product Type'])
print(df_grouped.groups)
display_all_groups(df_grouped)

{('NY', 'Desktop'): [24], ('NY', 'Laptop'): [19, 35], ('NY', 'Tablet'): [17, 34], ('OH', 'Desktop'): [0, 11, 31], ('OH', 'Laptop'): [6, 8, 16, 22, 26, 33], ('OH', 'Tablet'): [7, 14], ('PA', 'Desktop'): [2, 5, 13, 20, 36], ('PA', 'Laptop'): [3, 4, 10, 12, 15, 18, 21, 25, 27, 28, 30, 32, 37, 38], ('WV', 'Desktop'): [1, 9, 29], ('WV', 'Laptop'): [23]}
key:  ('NY', 'Desktop')
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
24,25,Michelle Samms,F,46,NY,I3670,Desktop,649.99,118.64,Flyer 2,November,2019

key:  ('NY', 'Laptop')
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
19,20,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2019
35,36,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2020

key:  ('NY', 'Tablet')
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
17,18,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,March,2019
34,35,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,April,2020

key:  ('OH', 'Desktop')
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
0,1,Paul Thomas,M,43,OH,M01-F0024,Desktop,479.99,143.39,Website,January,2018
11,12,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,November,2018
31,32,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,February,2020

key:  ('OH', 'Laptop')
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
6,7,Michelle Samms,F,46,OH,GA401IV,Laptop,1349.99,180.34,Email,May,2018
8,9,Ed Klondike,M,52,OH,81TC00,Laptop,649.99,122.34,Email,July,2018
16,17,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,February,2019
22,23,Paul Thomas,M,43,OH,81TC00,Laptop,649.99,122.34,Website,August,2019
26,27,Ed Klondike,M,52,OH,Q526FA,Laptop,1049.99,143.09,Website,December,2019
33,34,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,March,2020

key:  ('OH', 'Tablet')
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
7,8,Mick Roberts,M,23,OH,MY2J2LL,Tablet,999.99,146.69,Website,July,2018
14,15,Andy Sands,M,56,OH,MY2J2LL,Tablet,999.99,146.69,Flyer 1,December,2018

key:  ('PA', 'Desktop')
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
2,3,Sam Stine,M,26,PA,I3670,Desktop,649.99,118.64,Website,February,2018
5,6,Sally Struthers,F,45,PA,GT13-0024,Desktop,1249.99,230.89,Flyer 2,April,2018
13,14,Doug Johnson,M,51,PA,I3670,Desktop,649.99,118.64,Website,December,2018
20,21,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,May,2019
36,37,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,April,2020

key:  ('PA', 'Laptop')
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018
4,5,Jessica Elk,F,55,PA,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018
10,11,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 3,November,2018
12,13,Jason Case,M,57,PA,81TC00,Laptop,649.99,122.34,Email,November,2018
15,16,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,January,2019
18,19,Mick Roberts,M,23,PA,I3593,Laptop,399.99,72.09,Flyer 4,March,2019
21,22,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,August,2019
25,26,Mick Roberts,M,23,PA,Q526FA,Laptop,1049.99,143.09,Email,November,2019
27,28,Moe Eggert,M,35,PA,15M-ED,Laptop,699.99,98.09,Email,December,2019
28,29,Jessica Elk,F,55,PA,GA401IV,Laptop,1349.99,180.34,Flyer 2,December,2019
30,31,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 1,January,2020
32,33,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,March,2020
37,38,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,May,2020
38,39,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,May,2020

key:  ('WV', 'Desktop')
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
1,2,Margo Simms,F,37,WV,GT13-0024,Desktop,1249.99,230.89,Flyer 4,January,2018
9,10,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,August,2018
29,30,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,January,2020

key:  ('WV', 'Laptop')
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
23,24,Margo Simms,F,37,WV,Q526FA,Laptop,1049.99,143.09,Flyer 4,November,2019

### Groupby by provided values

In [55]:
df_grouped = df['Contact'].groupby(df['State'])
display_all_groups(df_grouped)

key:  NY
group:

17     Michelle Samms
19    Sally Struthers
24     Michelle Samms
34     Michelle Samms
35    Sally Struthers
Name: Contact, dtype: object

key:  OH
group:

0        Paul Thomas
6     Michelle Samms
7       Mick Roberts
8        Ed Klondike
11          Sue Etna
14        Andy Sands
16      Edna Sanders
22       Paul Thomas
26       Ed Klondike
31          Sue Etna
33      Edna Sanders
Name: Contact, dtype: object

key:  PA
group:

2           Sam Stine
3          Moe Eggert
4         Jessica Elk
5     Sally Struthers
10         Rick James
12         Jason Case
13       Doug Johnson
15        Kim Collins
18       Mick Roberts
20         Jason Case
21       Doug Johnson
25       Mick Roberts
27         Moe Eggert
28        Jessica Elk
30         Rick James
32        Kim Collins
36         Jason Case
37       Doug Johnson
38         Moe Eggert
Name: Contact, dtype: object

key:  WV
group:

1     Margo Simms
9      Phil Jones
23    Margo Simms
29     Phil Jones
Name: Contact, dtype: object

### Groupby by custom function values
function: idx -> value to be used for grouping

In [56]:
df

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
0,1,Paul Thomas,M,43,OH,M01-F0024,Desktop,479.99,143.39,Website,January,2018
1,2,Margo Simms,F,37,WV,GT13-0024,Desktop,1249.99,230.89,Flyer 4,January,2018
2,3,Sam Stine,M,26,PA,I3670,Desktop,649.99,118.64,Website,February,2018
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018
4,5,Jessica Elk,F,55,PA,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018
5,6,Sally Struthers,F,45,PA,GT13-0024,Desktop,1249.99,230.89,Flyer 2,April,2018
6,7,Michelle Samms,F,46,OH,GA401IV,Laptop,1349.99,180.34,Email,May,2018
7,8,Mick Roberts,M,23,OH,MY2J2LL,Tablet,999.99,146.69,Website,July,2018
8,9,Ed Klondike,M,52,OH,81TC00,Laptop,649.99,122.34,Email,July,2018
9,10,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,August,2018
10,11,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 3,November,2018
11,12,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,November,2018
12,13,Jason Case,M,57,PA,81TC00,Laptop,649.99,122.34,Email,November,2018
13,14,Doug Johnson,M,51,PA,I3670,Desktop,649.99,118.64,Website,December,2018
14,15,Andy Sands,M,56,OH,MY2J2LL,Tablet,999.99,146.69,Flyer 1,December,2018
15,16,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,January,2019
16,17,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,February,2019
17,18,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,March,2019
18,19,Mick Roberts,M,23,PA,I3593,Laptop,399.99,72.09,Flyer 4,March,2019
19,20,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2019
20,21,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,May,2019
21,22,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,August,2019
22,23,Paul Thomas,M,43,OH,81TC00,Laptop,649.99,122.34,Website,August,2019
23,24,Margo Simms,F,37,WV,Q526FA,Laptop,1049.99,143.09,Flyer 4,November,2019
24,25,Michelle Samms,F,46,NY,I3670,Desktop,649.99,118.64,Flyer 2,November,2019
25,26,Mick Roberts,M,23,PA,Q526FA,Laptop,1049.99,143.09,Email,November,2019
26,27,Ed Klondike,M,52,OH,Q526FA,Laptop,1049.99,143.09,Website,December,2019
27,28,Moe Eggert,M,35,PA,15M-ED,Laptop,699.99,98.09,Email,December,2019
28,29,Jessica Elk,F,55,PA,GA401IV,Laptop,1349.99,180.34,Flyer 2,December,2019
29,30,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,January,2020
30,31,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 1,January,2020
31,32,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,February,2020
32,33,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,March,2020
33,34,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,March,2020
34,35,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,April,2020
35,36,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2020
36,37,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,April,2020
37,38,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,May,2020
38,39,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,May,2020

In [57]:
def get_row_value(idx):
    return 'group'
df_grouped = df.groupby(by=get_row_value)
print(df_grouped.groups)
display_all_groups(df_grouped)

{'group': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38]}
key:  group
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
0,1,Paul Thomas,M,43,OH,M01-F0024,Desktop,479.99,143.39,Website,January,2018
1,2,Margo Simms,F,37,WV,GT13-0024,Desktop,1249.99,230.89,Flyer 4,January,2018
2,3,Sam Stine,M,26,PA,I3670,Desktop,649.99,118.64,Website,February,2018
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018
4,5,Jessica Elk,F,55,PA,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018
5,6,Sally Struthers,F,45,PA,GT13-0024,Desktop,1249.99,230.89,Flyer 2,April,2018
6,7,Michelle Samms,F,46,OH,GA401IV,Laptop,1349.99,180.34,Email,May,2018
7,8,Mick Roberts,M,23,OH,MY2J2LL,Tablet,999.99,146.69,Website,July,2018
8,9,Ed Klondike,M,52,OH,81TC00,Laptop,649.99,122.34,Email,July,2018
9,10,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,August,2018
10,11,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 3,November,2018
11,12,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,November,2018
12,13,Jason Case,M,57,PA,81TC00,Laptop,649.99,122.34,Email,November,2018
13,14,Doug Johnson,M,51,PA,I3670,Desktop,649.99,118.64,Website,December,2018
14,15,Andy Sands,M,56,OH,MY2J2LL,Tablet,999.99,146.69,Flyer 1,December,2018
15,16,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,January,2019
16,17,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,February,2019
17,18,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,March,2019
18,19,Mick Roberts,M,23,PA,I3593,Laptop,399.99,72.09,Flyer 4,March,2019
19,20,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2019
20,21,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,May,2019
21,22,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,August,2019
22,23,Paul Thomas,M,43,OH,81TC00,Laptop,649.99,122.34,Website,August,2019
23,24,Margo Simms,F,37,WV,Q526FA,Laptop,1049.99,143.09,Flyer 4,November,2019
24,25,Michelle Samms,F,46,NY,I3670,Desktop,649.99,118.64,Flyer 2,November,2019
25,26,Mick Roberts,M,23,PA,Q526FA,Laptop,1049.99,143.09,Email,November,2019
26,27,Ed Klondike,M,52,OH,Q526FA,Laptop,1049.99,143.09,Website,December,2019
27,28,Moe Eggert,M,35,PA,15M-ED,Laptop,699.99,98.09,Email,December,2019
28,29,Jessica Elk,F,55,PA,GA401IV,Laptop,1349.99,180.34,Flyer 2,December,2019
29,30,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,January,2020
30,31,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 1,January,2020
31,32,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,February,2020
32,33,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,March,2020
33,34,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,March,2020
34,35,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,April,2020
35,36,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2020
36,37,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,April,2020
37,38,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,May,2020
38,39,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,May,2020

In [58]:
def get_row_value(idx):
    return df.loc[idx,'State']

df_grouped = df.groupby(by=get_row_value)
print(df_grouped.groups)
display_all_groups(df_grouped)

{'NY': [17, 19, 24, 34, 35], 'OH': [0, 6, 7, 8, 11, 14, 16, 22, 26, 31, 33], 'PA': [2, 3, 4, 5, 10, 12, 13, 15, 18, 20, 21, 25, 27, 28, 30, 32, 36, 37, 38], 'WV': [1, 9, 23, 29]}
key:  NY
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
17,18,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,March,2019
19,20,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2019
24,25,Michelle Samms,F,46,NY,I3670,Desktop,649.99,118.64,Flyer 2,November,2019
34,35,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,April,2020
35,36,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2020

key:  OH
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
0,1,Paul Thomas,M,43,OH,M01-F0024,Desktop,479.99,143.39,Website,January,2018
6,7,Michelle Samms,F,46,OH,GA401IV,Laptop,1349.99,180.34,Email,May,2018
7,8,Mick Roberts,M,23,OH,MY2J2LL,Tablet,999.99,146.69,Website,July,2018
8,9,Ed Klondike,M,52,OH,81TC00,Laptop,649.99,122.34,Email,July,2018
11,12,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,November,2018
14,15,Andy Sands,M,56,OH,MY2J2LL,Tablet,999.99,146.69,Flyer 1,December,2018
16,17,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,February,2019
22,23,Paul Thomas,M,43,OH,81TC00,Laptop,649.99,122.34,Website,August,2019
26,27,Ed Klondike,M,52,OH,Q526FA,Laptop,1049.99,143.09,Website,December,2019
31,32,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,February,2020
33,34,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,March,2020

key:  PA
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
2,3,Sam Stine,M,26,PA,I3670,Desktop,649.99,118.64,Website,February,2018
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018
4,5,Jessica Elk,F,55,PA,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018
5,6,Sally Struthers,F,45,PA,GT13-0024,Desktop,1249.99,230.89,Flyer 2,April,2018
10,11,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 3,November,2018
12,13,Jason Case,M,57,PA,81TC00,Laptop,649.99,122.34,Email,November,2018
13,14,Doug Johnson,M,51,PA,I3670,Desktop,649.99,118.64,Website,December,2018
15,16,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,January,2019
18,19,Mick Roberts,M,23,PA,I3593,Laptop,399.99,72.09,Flyer 4,March,2019
20,21,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,May,2019
21,22,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,August,2019
25,26,Mick Roberts,M,23,PA,Q526FA,Laptop,1049.99,143.09,Email,November,2019
27,28,Moe Eggert,M,35,PA,15M-ED,Laptop,699.99,98.09,Email,December,2019
28,29,Jessica Elk,F,55,PA,GA401IV,Laptop,1349.99,180.34,Flyer 2,December,2019
30,31,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 1,January,2020
32,33,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,March,2020
36,37,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,April,2020
37,38,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,May,2020
38,39,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,May,2020

key:  WV
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
1,2,Margo Simms,F,37,WV,GT13-0024,Desktop,1249.99,230.89,Flyer 4,January,2018
9,10,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,August,2018
23,24,Margo Simms,F,37,WV,Q526FA,Laptop,1049.99,143.09,Flyer 4,November,2019
29,30,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,January,2020

In [59]:
# Answer
def get_row_value(idx):
    # idx -> value
    if df.loc[idx,'Age'] >= 20 and df.loc[idx,'Age'] < 30:
        return '20s'
    if df.loc[idx,'Age'] >= 30 and df.loc[idx, 'Age'] < 40:
        return '30s'
    if df.loc[idx,'Age'] >= 40:
        return '40+'

df_grouped = df.groupby(by=get_row_value)
# df_grouped = df.groupby(by='Age')
display_all_groups(df_grouped)

key:  20s
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
2,3,Sam Stine,M,26,PA,I3670,Desktop,649.99,118.64,Website,February,2018
7,8,Mick Roberts,M,23,OH,MY2J2LL,Tablet,999.99,146.69,Website,July,2018
18,19,Mick Roberts,M,23,PA,I3593,Laptop,399.99,72.09,Flyer 4,March,2019
25,26,Mick Roberts,M,23,PA,Q526FA,Laptop,1049.99,143.09,Email,November,2019

key:  30s
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
1,2,Margo Simms,F,37,WV,GT13-0024,Desktop,1249.99,230.89,Flyer 4,January,2018
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018
23,24,Margo Simms,F,37,WV,Q526FA,Laptop,1049.99,143.09,Flyer 4,November,2019
27,28,Moe Eggert,M,35,PA,15M-ED,Laptop,699.99,98.09,Email,December,2019
38,39,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,May,2020

key:  40+
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
0,1,Paul Thomas,M,43,OH,M01-F0024,Desktop,479.99,143.39,Website,January,2018
4,5,Jessica Elk,F,55,PA,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018
5,6,Sally Struthers,F,45,PA,GT13-0024,Desktop,1249.99,230.89,Flyer 2,April,2018
6,7,Michelle Samms,F,46,OH,GA401IV,Laptop,1349.99,180.34,Email,May,2018
8,9,Ed Klondike,M,52,OH,81TC00,Laptop,649.99,122.34,Email,July,2018
9,10,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,August,2018
10,11,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 3,November,2018
11,12,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,November,2018
12,13,Jason Case,M,57,PA,81TC00,Laptop,649.99,122.34,Email,November,2018
13,14,Doug Johnson,M,51,PA,I3670,Desktop,649.99,118.64,Website,December,2018
14,15,Andy Sands,M,56,OH,MY2J2LL,Tablet,999.99,146.69,Flyer 1,December,2018
15,16,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,January,2019
16,17,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,February,2019
17,18,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,March,2019
19,20,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2019
20,21,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,May,2019
21,22,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,August,2019
22,23,Paul Thomas,M,43,OH,81TC00,Laptop,649.99,122.34,Website,August,2019
24,25,Michelle Samms,F,46,NY,I3670,Desktop,649.99,118.64,Flyer 2,November,2019
26,27,Ed Klondike,M,52,OH,Q526FA,Laptop,1049.99,143.09,Website,December,2019
28,29,Jessica Elk,F,55,PA,GA401IV,Laptop,1349.99,180.34,Flyer 2,December,2019
29,30,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,January,2020
30,31,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 1,January,2020
31,32,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,February,2020
32,33,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,March,2020
33,34,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,March,2020
34,35,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,April,2020
35,36,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2020
36,37,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,April,2020
37,38,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,May,2020

## Apply: Aggregation, Transformation, Filter

### Aggregation (input function is: column series -> value)
https://stackoverflow.com/questions/27517425/apply-vs-transform-on-a-group-object
- mean()
- sum()
- size()
- count()
- std()
- var()
- sem()
- describe()
- first()
- last()
- nth()
- min()
- max()

In [60]:
df_grouped = df.groupby('Product Type')
display_all_groups(df_grouped)

key:  Desktop
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
0,1,Paul Thomas,M,43,OH,M01-F0024,Desktop,479.99,143.39,Website,January,2018
1,2,Margo Simms,F,37,WV,GT13-0024,Desktop,1249.99,230.89,Flyer 4,January,2018
2,3,Sam Stine,M,26,PA,I3670,Desktop,649.99,118.64,Website,February,2018
5,6,Sally Struthers,F,45,PA,GT13-0024,Desktop,1249.99,230.89,Flyer 2,April,2018
9,10,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,August,2018
11,12,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,November,2018
13,14,Doug Johnson,M,51,PA,I3670,Desktop,649.99,118.64,Website,December,2018
20,21,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,May,2019
24,25,Michelle Samms,F,46,NY,I3670,Desktop,649.99,118.64,Flyer 2,November,2019
29,30,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,January,2020
31,32,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,February,2020
36,37,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,April,2020

key:  Laptop
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018
4,5,Jessica Elk,F,55,PA,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018
6,7,Michelle Samms,F,46,OH,GA401IV,Laptop,1349.99,180.34,Email,May,2018
8,9,Ed Klondike,M,52,OH,81TC00,Laptop,649.99,122.34,Email,July,2018
10,11,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 3,November,2018
12,13,Jason Case,M,57,PA,81TC00,Laptop,649.99,122.34,Email,November,2018
15,16,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,January,2019
16,17,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,February,2019
18,19,Mick Roberts,M,23,PA,I3593,Laptop,399.99,72.09,Flyer 4,March,2019
19,20,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2019
21,22,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,August,2019
22,23,Paul Thomas,M,43,OH,81TC00,Laptop,649.99,122.34,Website,August,2019
23,24,Margo Simms,F,37,WV,Q526FA,Laptop,1049.99,143.09,Flyer 4,November,2019
25,26,Mick Roberts,M,23,PA,Q526FA,Laptop,1049.99,143.09,Email,November,2019
26,27,Ed Klondike,M,52,OH,Q526FA,Laptop,1049.99,143.09,Website,December,2019
27,28,Moe Eggert,M,35,PA,15M-ED,Laptop,699.99,98.09,Email,December,2019
28,29,Jessica Elk,F,55,PA,GA401IV,Laptop,1349.99,180.34,Flyer 2,December,2019
30,31,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 1,January,2020
32,33,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,March,2020
33,34,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,March,2020
35,36,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2020
37,38,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,May,2020
38,39,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,May,2020

key:  Tablet
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
7,8,Mick Roberts,M,23,OH,MY2J2LL,Tablet,999.99,146.69,Website,July,2018
14,15,Andy Sands,M,56,OH,MY2J2LL,Tablet,999.99,146.69,Flyer 1,December,2018
17,18,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,March,2019
34,35,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,April,2020

In [61]:
import numpy as np
#---------------------------------------------
#* single function *
# compute sum of each group
display(df_grouped.sum())
display(df_grouped.agg(func=sum))
display(df_grouped.agg(func='sum'))
display(df_grouped.agg(func=np.sum))

# compute size of each group
display(df_grouped.size())
display(df_grouped.agg(func='size'))

# compute describe of each group
display(df_grouped.describe())
display(df_grouped.agg(func='describe'))

# custom function, lambda function
display(df_grouped.agg(func=np.max))
display(df_grouped.agg(func=np.min))

,Sale ID,Contact,Sex,Age,State,Product ID,Sale Price,Profit,Lead,Month,Year
Product Type,,,,,,,,,,,
Desktop,193,Paul ThomasMargo SimmsSam StineSally Struthers...,MFMFMFMMFMFM,582,OHWVPAPAWVOHPAPANYWVOHPA,M01-F0024GT13-0024I3670GT13-0024M01-F0024GT13-...,9349.88,1996.43,WebsiteFlyer 4WebsiteFlyer 2Flyer 2Flyer 2Webs...,JanuaryJanuaryFebruaryAprilAugustNovemberDecem...,24224
Laptop,511,Moe EggertJessica ElkMichelle SammsEd Klondike...,MFFMMMFFMFMMFMMMFMFFFMM,1028,PAPAOHOHPAPAPAOHPANYPAOHWVPAOHPAPAPAPAOHNYPAPA,I359315M-EDGA401IV81TC00GA401IV81TC00I359315M-...,19299.77,2875.82,WebsiteFlyer 4EmailEmailFlyer 3EmailFlyer 2Ema...,MarchMarchMayJulyNovemberNovemberJanuaryFebrua...,46437
Tablet,76,Mick RobertsAndy SandsMichelle SammsMichelle S...,MMFF,171,OHOHNYNY,MY2J2LLMY2J2LLMY2J2LLMY2J2LL,3999.96,586.76,WebsiteFlyer 1WebsiteWebsite,JulyDecemberMarchApril,8075

/var/folders/z4/cyv0pfhs0sb3531vj7glg5g00000gn/T/ipykernel_77650/854209650.py:6: FutureWarning: The provided callable <built-in function sum> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  display(df_grouped.agg(func=sum))

,Sale ID,Contact,Sex,Age,State,Product ID,Sale Price,Profit,Lead,Month,Year
Product Type,,,,,,,,,,,
Desktop,193,Paul ThomasMargo SimmsSam StineSally Struthers...,MFMFMFMMFMFM,582,OHWVPAPAWVOHPAPANYWVOHPA,M01-F0024GT13-0024I3670GT13-0024M01-F0024GT13-...,9349.88,1996.43,WebsiteFlyer 4WebsiteFlyer 2Flyer 2Flyer 2Webs...,JanuaryJanuaryFebruaryAprilAugustNovemberDecem...,24224
Laptop,511,Moe EggertJessica ElkMichelle SammsEd Klondike...,MFFMMMFFMFMMFMMMFMFFFMM,1028,PAPAOHOHPAPAPAOHPANYPAOHWVPAOHPAPAPAPAOHNYPAPA,I359315M-EDGA401IV81TC00GA401IV81TC00I359315M-...,19299.77,2875.82,WebsiteFlyer 4EmailEmailFlyer 3EmailFlyer 2Ema...,MarchMarchMayJulyNovemberNovemberJanuaryFebrua...,46437
Tablet,76,Mick RobertsAndy SandsMichelle SammsMichelle S...,MMFF,171,OHOHNYNY,MY2J2LLMY2J2LLMY2J2LLMY2J2LL,3999.96,586.76,WebsiteFlyer 1WebsiteWebsite,JulyDecemberMarchApril,8075

,Sale ID,Contact,Sex,Age,State,Product ID,Sale Price,Profit,Lead,Month,Year
Product Type,,,,,,,,,,,
Desktop,193,Paul ThomasMargo SimmsSam StineSally Struthers...,MFMFMFMMFMFM,582,OHWVPAPAWVOHPAPANYWVOHPA,M01-F0024GT13-0024I3670GT13-0024M01-F0024GT13-...,9349.88,1996.43,WebsiteFlyer 4WebsiteFlyer 2Flyer 2Flyer 2Webs...,JanuaryJanuaryFebruaryAprilAugustNovemberDecem...,24224
Laptop,511,Moe EggertJessica ElkMichelle SammsEd Klondike...,MFFMMMFFMFMMFMMMFMFFFMM,1028,PAPAOHOHPAPAPAOHPANYPAOHWVPAOHPAPAPAPAOHNYPAPA,I359315M-EDGA401IV81TC00GA401IV81TC00I359315M-...,19299.77,2875.82,WebsiteFlyer 4EmailEmailFlyer 3EmailFlyer 2Ema...,MarchMarchMayJulyNovemberNovemberJanuaryFebrua...,46437
Tablet,76,Mick RobertsAndy SandsMichelle SammsMichelle S...,MMFF,171,OHOHNYNY,MY2J2LLMY2J2LLMY2J2LLMY2J2LL,3999.96,586.76,WebsiteFlyer 1WebsiteWebsite,JulyDecemberMarchApril,8075

/var/folders/z4/cyv0pfhs0sb3531vj7glg5g00000gn/T/ipykernel_77650/854209650.py:8: FutureWarning: The provided callable <function sum at 0x111945900> is currently using DataFrameGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  display(df_grouped.agg(func=np.sum))

,Sale ID,Contact,Sex,Age,State,Product ID,Sale Price,Profit,Lead,Month,Year
Product Type,,,,,,,,,,,
Desktop,193,Paul ThomasMargo SimmsSam StineSally Struthers...,MFMFMFMMFMFM,582,OHWVPAPAWVOHPAPANYWVOHPA,M01-F0024GT13-0024I3670GT13-0024M01-F0024GT13-...,9349.88,1996.43,WebsiteFlyer 4WebsiteFlyer 2Flyer 2Flyer 2Webs...,JanuaryJanuaryFebruaryAprilAugustNovemberDecem...,24224
Laptop,511,Moe EggertJessica ElkMichelle SammsEd Klondike...,MFFMMMFFMFMMFMMMFMFFFMM,1028,PAPAOHOHPAPAPAOHPANYPAOHWVPAOHPAPAPAPAOHNYPAPA,I359315M-EDGA401IV81TC00GA401IV81TC00I359315M-...,19299.77,2875.82,WebsiteFlyer 4EmailEmailFlyer 3EmailFlyer 2Ema...,MarchMarchMayJulyNovemberNovemberJanuaryFebrua...,46437
Tablet,76,Mick RobertsAndy SandsMichelle SammsMichelle S...,MMFF,171,OHOHNYNY,MY2J2LLMY2J2LLMY2J2LLMY2J2LL,3999.96,586.76,WebsiteFlyer 1WebsiteWebsite,JulyDecemberMarchApril,8075

Product Type
Desktop    12
Laptop     23
Tablet      4
dtype: int64

Product Type
Desktop    12
Laptop     23
Tablet      4
dtype: int64

             Sale ID                                                       \
               count       mean        std  min    25%   50%    75%   max
Product Type
Desktop         12.0  16.083333  12.594792  1.0   5.25  13.0  26.25  37.0
Laptop          23.0  22.217391  10.659850  4.0  14.50  23.0  30.00  39.0
Tablet           4.0  19.000000  11.460076  8.0  13.25  16.5  22.25  35.0

               Age             ...   Profit          Year               \
             count       mean  ...      75%     max count         mean
Product Type                   ...
Desktop       12.0  48.500000  ...  230.890  230.89  12.0  2018.666667
Laptop        23.0  44.695652  ...  161.715  180.34  23.0  2019.000000
Tablet         4.0  42.750000  ...  146.690  146.69   4.0  2018.750000


                   std     min     25%     50%      75%     max
Product Type
Desktop       0.887625  2018.0  2018.0  2018.0  2019.25  2020.0
Laptop        0.738549  2018.0  2018.5  2019.0  2019.50  2020.0
Tablet        0.957427  2018.0  2018.0  2018.5  2019.25  2020.0

[3 rows x 40 columns]

             Sale ID                                                       \
               count       mean        std  min    25%   50%    75%   max
Product Type
Desktop         12.0  16.083333  12.594792  1.0   5.25  13.0  26.25  37.0
Laptop          23.0  22.217391  10.659850  4.0  14.50  23.0  30.00  39.0
Tablet           4.0  19.000000  11.460076  8.0  13.25  16.5  22.25  35.0

               Age             ...   Profit          Year               \
             count       mean  ...      75%     max count         mean
Product Type                   ...
Desktop       12.0  48.500000  ...  230.890  230.89  12.0  2018.666667
Laptop        23.0  44.695652  ...  161.715  180.34  23.0  2019.000000
Tablet         4.0  42.750000  ...  146.690  146.69   4.0  2018.750000


                   std     min     25%     50%      75%     max
Product Type
Desktop       0.887625  2018.0  2018.0  2018.0  2019.25  2020.0
Laptop        0.738549  2018.0  2018.5  2019.0  2019.50  2020.0
Tablet        0.957427  2018.0  2018.0  2018.5  2019.25  2020.0

[3 rows x 40 columns]

/var/folders/z4/cyv0pfhs0sb3531vj7glg5g00000gn/T/ipykernel_77650/854209650.py:19: FutureWarning: The provided callable <function max at 0x111946200> is currently using DataFrameGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  display(df_grouped.agg(func=np.max))

,Sale ID,Contact,Sex,Age,State,Product ID,Sale Price,Profit,Lead,Month,Year
Product Type,,,,,,,,,,,
Desktop,37,Sue Etna,M,57,WV,M01-F0024,1249.99,230.89,Website,November,2020
Laptop,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
Tablet,35,Mick Roberts,M,56,OH,MY2J2LL,999.99,146.69,Website,March,2020

/var/folders/z4/cyv0pfhs0sb3531vj7glg5g00000gn/T/ipykernel_77650/854209650.py:20: FutureWarning: The provided callable <function min at 0x111946320> is currently using DataFrameGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  display(df_grouped.agg(func=np.min))

,Sale ID,Contact,Sex,Age,State,Product ID,Sale Price,Profit,Lead,Month,Year
Product Type,,,,,,,,,,,
Desktop,1,Doug Johnson,F,26,NY,GT13-0024,479.99,118.64,Flyer 2,April,2018
Laptop,4,Doug Johnson,F,23,NY,15M-ED,399.99,72.09,Email,April,2018
Tablet,8,Andy Sands,F,23,NY,MY2J2LL,999.99,146.69,Flyer 1,April,2018

In [62]:
# Answer
def agg_f(column):
    #print(group)
    return np.max(column) - np.min(column)

display(df_grouped['Age'].agg(func=agg_f))

Product Type
Desktop    31
Laptop     34
Tablet     33
Name: Age, dtype: int64

In [63]:
#* multiple functions *
display(df_grouped['Age'].agg(func=[np.sum, np.mean]))

/var/folders/z4/cyv0pfhs0sb3531vj7glg5g00000gn/T/ipykernel_77650/4286494131.py:2: FutureWarning: The provided callable <function sum at 0x111945900> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  display(df_grouped['Age'].agg(func=[np.sum, np.mean]))
/var/folders/z4/cyv0pfhs0sb3531vj7glg5g00000gn/T/ipykernel_77650/4286494131.py:2: FutureWarning: The provided callable <function mean at 0x111946b00> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  display(df_grouped['Age'].agg(func=[np.sum, np.mean]))

               sum       mean
Product Type
Desktop        582  48.500000
Laptop        1028  44.695652
Tablet         171  42.750000

In [64]:
#* different function for different column *
display(df_grouped.agg(func={'Age': np.sum, 'Sale Price': np.mean}))

/var/folders/z4/cyv0pfhs0sb3531vj7glg5g00000gn/T/ipykernel_77650/2459680255.py:2: FutureWarning: The provided callable <function sum at 0x111945900> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  display(df_grouped.agg(func={'Age': np.sum, 'Sale Price': np.mean}))
/var/folders/z4/cyv0pfhs0sb3531vj7glg5g00000gn/T/ipykernel_77650/2459680255.py:2: FutureWarning: The provided callable <function mean at 0x111946b00> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  display(df_grouped.agg(func={'Age': np.sum, 'Sale Price': np.mean}))

               Age  Sale Price
Product Type
Desktop        582  779.156667
Laptop        1028  839.120435
Tablet         171  999.990000

In [65]:
# Named Aggregation: https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#named-aggregation
display(df_grouped.agg(sum_age=('Age', np.sum), mean_price=('Sale Price', np.mean)))

/var/folders/z4/cyv0pfhs0sb3531vj7glg5g00000gn/T/ipykernel_77650/3910909481.py:2: FutureWarning: The provided callable <function sum at 0x111945900> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  display(df_grouped.agg(sum_age=('Age', np.sum), mean_price=('Sale Price', np.mean)))
/var/folders/z4/cyv0pfhs0sb3531vj7glg5g00000gn/T/ipykernel_77650/3910909481.py:2: FutureWarning: The provided callable <function mean at 0x111946b00> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  display(df_grouped.agg(sum_age=('Age', np.sum), mean_price=('Sale Price', np.mean)))

              sum_age  mean_price
Product Type
Desktop           582  779.156667
Laptop           1028  839.120435
Tablet            171  999.990000

## Group Practice

Work in groups of 2–3 students.

Using `computerSales.csv`, create a summary table with **one row for each state**. Your summary should include:

1. The **number of sales**
2. The **mean sale price**
3. The **total profit**

Then sort the summary table from the **highest to the lowest mean sale price**.

Each group should be ready to explain at least **one line of your code**.

In [66]:
# write your code here

> **Note**
>
> - `size()` counts the **number of rows** in each group.
> - `count()` counts the **number of non-missing values** in a selected column.
> - If there are no missing values, `size()` and `count()` may give the same result.
> - For this task, `size()` is a clearer choice because we want to count the total number of sales.

# 4th week recitation

### Transformation (input function is: column series -> value or list)

In [67]:
import copy
# broadcast: same size as previous dataset
display(df)

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
0,1,Paul Thomas,M,43,OH,M01-F0024,Desktop,479.99,143.39,Website,January,2018
1,2,Margo Simms,F,37,WV,GT13-0024,Desktop,1249.99,230.89,Flyer 4,January,2018
2,3,Sam Stine,M,26,PA,I3670,Desktop,649.99,118.64,Website,February,2018
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018
4,5,Jessica Elk,F,55,PA,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018
5,6,Sally Struthers,F,45,PA,GT13-0024,Desktop,1249.99,230.89,Flyer 2,April,2018
6,7,Michelle Samms,F,46,OH,GA401IV,Laptop,1349.99,180.34,Email,May,2018
7,8,Mick Roberts,M,23,OH,MY2J2LL,Tablet,999.99,146.69,Website,July,2018
8,9,Ed Klondike,M,52,OH,81TC00,Laptop,649.99,122.34,Email,July,2018
9,10,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,August,2018
10,11,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 3,November,2018
11,12,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,November,2018
12,13,Jason Case,M,57,PA,81TC00,Laptop,649.99,122.34,Email,November,2018
13,14,Doug Johnson,M,51,PA,I3670,Desktop,649.99,118.64,Website,December,2018
14,15,Andy Sands,M,56,OH,MY2J2LL,Tablet,999.99,146.69,Flyer 1,December,2018
15,16,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,January,2019
16,17,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,February,2019
17,18,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,March,2019
18,19,Mick Roberts,M,23,PA,I3593,Laptop,399.99,72.09,Flyer 4,March,2019
19,20,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2019
20,21,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,May,2019
21,22,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,August,2019
22,23,Paul Thomas,M,43,OH,81TC00,Laptop,649.99,122.34,Website,August,2019
23,24,Margo Simms,F,37,WV,Q526FA,Laptop,1049.99,143.09,Flyer 4,November,2019
24,25,Michelle Samms,F,46,NY,I3670,Desktop,649.99,118.64,Flyer 2,November,2019
25,26,Mick Roberts,M,23,PA,Q526FA,Laptop,1049.99,143.09,Email,November,2019
26,27,Ed Klondike,M,52,OH,Q526FA,Laptop,1049.99,143.09,Website,December,2019
27,28,Moe Eggert,M,35,PA,15M-ED,Laptop,699.99,98.09,Email,December,2019
28,29,Jessica Elk,F,55,PA,GA401IV,Laptop,1349.99,180.34,Flyer 2,December,2019
29,30,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,January,2020
30,31,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 1,January,2020
31,32,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,February,2020
32,33,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,March,2020
33,34,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,March,2020
34,35,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,April,2020
35,36,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2020
36,37,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,April,2020
37,38,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,May,2020
38,39,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,May,2020

In [68]:
df_grouped = df.groupby('Product Type')
display_all_groups(df_grouped)

key:  Desktop
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
0,1,Paul Thomas,M,43,OH,M01-F0024,Desktop,479.99,143.39,Website,January,2018
1,2,Margo Simms,F,37,WV,GT13-0024,Desktop,1249.99,230.89,Flyer 4,January,2018
2,3,Sam Stine,M,26,PA,I3670,Desktop,649.99,118.64,Website,February,2018
5,6,Sally Struthers,F,45,PA,GT13-0024,Desktop,1249.99,230.89,Flyer 2,April,2018
9,10,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,August,2018
11,12,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,November,2018
13,14,Doug Johnson,M,51,PA,I3670,Desktop,649.99,118.64,Website,December,2018
20,21,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,May,2019
24,25,Michelle Samms,F,46,NY,I3670,Desktop,649.99,118.64,Flyer 2,November,2019
29,30,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,January,2020
31,32,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,February,2020
36,37,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,April,2020

key:  Laptop
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018
4,5,Jessica Elk,F,55,PA,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018
6,7,Michelle Samms,F,46,OH,GA401IV,Laptop,1349.99,180.34,Email,May,2018
8,9,Ed Klondike,M,52,OH,81TC00,Laptop,649.99,122.34,Email,July,2018
10,11,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 3,November,2018
12,13,Jason Case,M,57,PA,81TC00,Laptop,649.99,122.34,Email,November,2018
15,16,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,January,2019
16,17,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,February,2019
18,19,Mick Roberts,M,23,PA,I3593,Laptop,399.99,72.09,Flyer 4,March,2019
19,20,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2019
21,22,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,August,2019
22,23,Paul Thomas,M,43,OH,81TC00,Laptop,649.99,122.34,Website,August,2019
23,24,Margo Simms,F,37,WV,Q526FA,Laptop,1049.99,143.09,Flyer 4,November,2019
25,26,Mick Roberts,M,23,PA,Q526FA,Laptop,1049.99,143.09,Email,November,2019
26,27,Ed Klondike,M,52,OH,Q526FA,Laptop,1049.99,143.09,Website,December,2019
27,28,Moe Eggert,M,35,PA,15M-ED,Laptop,699.99,98.09,Email,December,2019
28,29,Jessica Elk,F,55,PA,GA401IV,Laptop,1349.99,180.34,Flyer 2,December,2019
30,31,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 1,January,2020
32,33,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,March,2020
33,34,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,March,2020
35,36,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2020
37,38,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,May,2020
38,39,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,May,2020

key:  Tablet
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
7,8,Mick Roberts,M,23,OH,MY2J2LL,Tablet,999.99,146.69,Website,July,2018
14,15,Andy Sands,M,56,OH,MY2J2LL,Tablet,999.99,146.69,Flyer 1,December,2018
17,18,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,March,2019
34,35,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,April,2020

In [69]:
# transform returns output aligned with the original rows.
display(df_grouped.transform(func=np.max))

/var/folders/z4/cyv0pfhs0sb3531vj7glg5g00000gn/T/ipykernel_77650/1332311990.py:2: FutureWarning: The provided callable <function max at 0x111946200> is currently using DataFrameGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  display(df_grouped.transform(func=np.max))

,Sale ID,Contact,Sex,Age,State,Product ID,Sale Price,Profit,Lead,Month,Year
0,37,Sue Etna,M,57,WV,M01-F0024,1249.99,230.89,Website,November,2020
1,37,Sue Etna,M,57,WV,M01-F0024,1249.99,230.89,Website,November,2020
2,37,Sue Etna,M,57,WV,M01-F0024,1249.99,230.89,Website,November,2020
3,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
4,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
5,37,Sue Etna,M,57,WV,M01-F0024,1249.99,230.89,Website,November,2020
6,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
7,35,Mick Roberts,M,56,OH,MY2J2LL,999.99,146.69,Website,March,2020
8,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
9,37,Sue Etna,M,57,WV,M01-F0024,1249.99,230.89,Website,November,2020
10,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
11,37,Sue Etna,M,57,WV,M01-F0024,1249.99,230.89,Website,November,2020
12,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
13,37,Sue Etna,M,57,WV,M01-F0024,1249.99,230.89,Website,November,2020
14,35,Mick Roberts,M,56,OH,MY2J2LL,999.99,146.69,Website,March,2020
15,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
16,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
17,35,Mick Roberts,M,56,OH,MY2J2LL,999.99,146.69,Website,March,2020
18,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
19,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
20,37,Sue Etna,M,57,WV,M01-F0024,1249.99,230.89,Website,November,2020
21,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
22,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
23,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
24,37,Sue Etna,M,57,WV,M01-F0024,1249.99,230.89,Website,November,2020
25,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
26,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
27,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
28,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
29,37,Sue Etna,M,57,WV,M01-F0024,1249.99,230.89,Website,November,2020
30,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
31,37,Sue Etna,M,57,WV,M01-F0024,1249.99,230.89,Website,November,2020
32,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
33,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
34,35,Mick Roberts,M,56,OH,MY2J2LL,999.99,146.69,Website,March,2020
35,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
36,37,Sue Etna,M,57,WV,M01-F0024,1249.99,230.89,Website,November,2020
37,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020
38,39,Sally Struthers,M,57,WV,Q526FA,1349.99,180.34,Website,November,2020

In [70]:
def tran_f(column):
    #input: column
    #output: Series same length as column
    if column.name == 'Product ID':
        return column.str[:3]
    else:
        return column

display(df_grouped.transform(tran_f))

,Sale ID,Contact,Sex,Age,State,Product ID,Sale Price,Profit,Lead,Month,Year
0,1,Paul Thomas,M,43,OH,M01,479.99,143.39,Website,January,2018
1,2,Margo Simms,F,37,WV,GT1,1249.99,230.89,Flyer 4,January,2018
2,3,Sam Stine,M,26,PA,I36,649.99,118.64,Website,February,2018
3,4,Moe Eggert,M,35,PA,I35,399.99,72.09,Website,March,2018
4,5,Jessica Elk,F,55,PA,15M,699.99,98.09,Flyer 4,March,2018
5,6,Sally Struthers,F,45,PA,GT1,1249.99,230.89,Flyer 2,April,2018
6,7,Michelle Samms,F,46,OH,GA4,1349.99,180.34,Email,May,2018
7,8,Mick Roberts,M,23,OH,MY2,999.99,146.69,Website,July,2018
8,9,Ed Klondike,M,52,OH,81T,649.99,122.34,Email,July,2018
9,10,Phil Jones,M,56,WV,M01,479.99,143.39,Flyer 2,August,2018
10,11,Rick James,M,49,PA,GA4,1349.99,180.34,Flyer 3,November,2018
11,12,Sue Etna,F,54,OH,GT1,1249.99,230.89,Flyer 2,November,2018
12,13,Jason Case,M,57,PA,81T,649.99,122.34,Email,November,2018
13,14,Doug Johnson,M,51,PA,I36,649.99,118.64,Website,December,2018
14,15,Andy Sands,M,56,OH,MY2,999.99,146.69,Flyer 1,December,2018
15,16,Kim Collins,F,49,PA,I35,399.99,72.09,Flyer 2,January,2019
16,17,Edna Sanders,F,46,OH,15M,699.99,98.09,Email,February,2019
17,18,Michelle Samms,F,46,NY,MY2,999.99,146.69,Website,March,2019
18,19,Mick Roberts,M,23,PA,I35,399.99,72.09,Flyer 4,March,2019
19,20,Sally Struthers,F,45,NY,81T,649.99,122.34,Website,April,2019
20,21,Jason Case,M,57,PA,M01,479.99,143.39,Flyer 4,May,2019
21,22,Doug Johnson,M,51,PA,GA4,1349.99,180.34,Website,August,2019
22,23,Paul Thomas,M,43,OH,81T,649.99,122.34,Website,August,2019
23,24,Margo Simms,F,37,WV,Q52,1049.99,143.09,Flyer 4,November,2019
24,25,Michelle Samms,F,46,NY,I36,649.99,118.64,Flyer 2,November,2019
25,26,Mick Roberts,M,23,PA,Q52,1049.99,143.09,Email,November,2019
26,27,Ed Klondike,M,52,OH,Q52,1049.99,143.09,Website,December,2019
27,28,Moe Eggert,M,35,PA,15M,699.99,98.09,Email,December,2019
28,29,Jessica Elk,F,55,PA,GA4,1349.99,180.34,Flyer 2,December,2019
29,30,Phil Jones,M,56,WV,M01,479.99,143.39,Flyer 2,January,2020
30,31,Rick James,M,49,PA,GA4,1349.99,180.34,Flyer 1,January,2020
31,32,Sue Etna,F,54,OH,GT1,1249.99,230.89,Flyer 2,February,2020
32,33,Kim Collins,F,49,PA,I35,399.99,72.09,Flyer 2,March,2020
33,34,Edna Sanders,F,46,OH,15M,699.99,98.09,Email,March,2020
34,35,Michelle Samms,F,46,NY,MY2,999.99,146.69,Website,April,2020
35,36,Sally Struthers,F,45,NY,81T,649.99,122.34,Website,April,2020
36,37,Jason Case,M,57,PA,M01,479.99,143.39,Flyer 4,April,2020
37,38,Doug Johnson,M,51,PA,GA4,1349.99,180.34,Website,May,2020
38,39,Moe Eggert,M,35,PA,I35,399.99,72.09,Website,May,2020

In [71]:
def tran_f(column):
    if column.name == 'Sale Price':
        return column - column.mean()
    else:
        return column
display(df_grouped.transform(tran_f))

,Sale ID,Contact,Sex,Age,State,Product ID,Sale Price,Profit,Lead,Month,Year
0,1,Paul Thomas,M,43,OH,M01-F0024,-299.166667,143.39,Website,January,2018
1,2,Margo Simms,F,37,WV,GT13-0024,470.833333,230.89,Flyer 4,January,2018
2,3,Sam Stine,M,26,PA,I3670,-129.166667,118.64,Website,February,2018
3,4,Moe Eggert,M,35,PA,I3593,-439.130435,72.09,Website,March,2018
4,5,Jessica Elk,F,55,PA,15M-ED,-139.130435,98.09,Flyer 4,March,2018
5,6,Sally Struthers,F,45,PA,GT13-0024,470.833333,230.89,Flyer 2,April,2018
6,7,Michelle Samms,F,46,OH,GA401IV,510.869565,180.34,Email,May,2018
7,8,Mick Roberts,M,23,OH,MY2J2LL,0.000000,146.69,Website,July,2018
8,9,Ed Klondike,M,52,OH,81TC00,-189.130435,122.34,Email,July,2018
9,10,Phil Jones,M,56,WV,M01-F0024,-299.166667,143.39,Flyer 2,August,2018
10,11,Rick James,M,49,PA,GA401IV,510.869565,180.34,Flyer 3,November,2018
11,12,Sue Etna,F,54,OH,GT13-0024,470.833333,230.89,Flyer 2,November,2018
12,13,Jason Case,M,57,PA,81TC00,-189.130435,122.34,Email,November,2018
13,14,Doug Johnson,M,51,PA,I3670,-129.166667,118.64,Website,December,2018
14,15,Andy Sands,M,56,OH,MY2J2LL,0.000000,146.69,Flyer 1,December,2018
15,16,Kim Collins,F,49,PA,I3593,-439.130435,72.09,Flyer 2,January,2019
16,17,Edna Sanders,F,46,OH,15M-ED,-139.130435,98.09,Email,February,2019
17,18,Michelle Samms,F,46,NY,MY2J2LL,0.000000,146.69,Website,March,2019
18,19,Mick Roberts,M,23,PA,I3593,-439.130435,72.09,Flyer 4,March,2019
19,20,Sally Struthers,F,45,NY,81TC00,-189.130435,122.34,Website,April,2019
20,21,Jason Case,M,57,PA,M01-F0024,-299.166667,143.39,Flyer 4,May,2019
21,22,Doug Johnson,M,51,PA,GA401IV,510.869565,180.34,Website,August,2019
22,23,Paul Thomas,M,43,OH,81TC00,-189.130435,122.34,Website,August,2019
23,24,Margo Simms,F,37,WV,Q526FA,210.869565,143.09,Flyer 4,November,2019
24,25,Michelle Samms,F,46,NY,I3670,-129.166667,118.64,Flyer 2,November,2019
25,26,Mick Roberts,M,23,PA,Q526FA,210.869565,143.09,Email,November,2019
26,27,Ed Klondike,M,52,OH,Q526FA,210.869565,143.09,Website,December,2019
27,28,Moe Eggert,M,35,PA,15M-ED,-139.130435,98.09,Email,December,2019
28,29,Jessica Elk,F,55,PA,GA401IV,510.869565,180.34,Flyer 2,December,2019
29,30,Phil Jones,M,56,WV,M01-F0024,-299.166667,143.39,Flyer 2,January,2020
30,31,Rick James,M,49,PA,GA401IV,510.869565,180.34,Flyer 1,January,2020
31,32,Sue Etna,F,54,OH,GT13-0024,470.833333,230.89,Flyer 2,February,2020
32,33,Kim Collins,F,49,PA,I3593,-439.130435,72.09,Flyer 2,March,2020
33,34,Edna Sanders,F,46,OH,15M-ED,-139.130435,98.09,Email,March,2020
34,35,Michelle Samms,F,46,NY,MY2J2LL,0.000000,146.69,Website,April,2020
35,36,Sally Struthers,F,45,NY,81TC00,-189.130435,122.34,Website,April,2020
36,37,Jason Case,M,57,PA,M01-F0024,-299.166667,143.39,Flyer 4,April,2020
37,38,Doug Johnson,M,51,PA,GA401IV,510.869565,180.34,Website,May,2020
38,39,Moe Eggert,M,35,PA,I3593,-439.130435,72.09,Website,May,2020

### Filter
https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#filtration
#### NOTE: The argument of filter must be a function that, applied to the group as a whole, returns True or False.

In [72]:
display_all_groups(df_grouped)

key:  Desktop
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
0,1,Paul Thomas,M,43,OH,M01-F0024,Desktop,479.99,143.39,Website,January,2018
1,2,Margo Simms,F,37,WV,GT13-0024,Desktop,1249.99,230.89,Flyer 4,January,2018
2,3,Sam Stine,M,26,PA,I3670,Desktop,649.99,118.64,Website,February,2018
5,6,Sally Struthers,F,45,PA,GT13-0024,Desktop,1249.99,230.89,Flyer 2,April,2018
9,10,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,August,2018
11,12,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,November,2018
13,14,Doug Johnson,M,51,PA,I3670,Desktop,649.99,118.64,Website,December,2018
20,21,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,May,2019
24,25,Michelle Samms,F,46,NY,I3670,Desktop,649.99,118.64,Flyer 2,November,2019
29,30,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,January,2020
31,32,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,February,2020
36,37,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,April,2020

key:  Laptop
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018
4,5,Jessica Elk,F,55,PA,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018
6,7,Michelle Samms,F,46,OH,GA401IV,Laptop,1349.99,180.34,Email,May,2018
8,9,Ed Klondike,M,52,OH,81TC00,Laptop,649.99,122.34,Email,July,2018
10,11,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 3,November,2018
12,13,Jason Case,M,57,PA,81TC00,Laptop,649.99,122.34,Email,November,2018
15,16,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,January,2019
16,17,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,February,2019
18,19,Mick Roberts,M,23,PA,I3593,Laptop,399.99,72.09,Flyer 4,March,2019
19,20,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2019
21,22,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,August,2019
22,23,Paul Thomas,M,43,OH,81TC00,Laptop,649.99,122.34,Website,August,2019
23,24,Margo Simms,F,37,WV,Q526FA,Laptop,1049.99,143.09,Flyer 4,November,2019
25,26,Mick Roberts,M,23,PA,Q526FA,Laptop,1049.99,143.09,Email,November,2019
26,27,Ed Klondike,M,52,OH,Q526FA,Laptop,1049.99,143.09,Website,December,2019
27,28,Moe Eggert,M,35,PA,15M-ED,Laptop,699.99,98.09,Email,December,2019
28,29,Jessica Elk,F,55,PA,GA401IV,Laptop,1349.99,180.34,Flyer 2,December,2019
30,31,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 1,January,2020
32,33,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,March,2020
33,34,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,March,2020
35,36,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2020
37,38,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,May,2020
38,39,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,May,2020

key:  Tablet
group:

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
7,8,Mick Roberts,M,23,OH,MY2J2LL,Tablet,999.99,146.69,Website,July,2018
14,15,Andy Sands,M,56,OH,MY2J2LL,Tablet,999.99,146.69,Flyer 1,December,2018
17,18,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,March,2019
34,35,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,April,2020

In [73]:
# only keep group with more than 2 elements
def filter_f(group):
    return len(group) >= 10

# If the function returns True, pandas keeps the entire group.
# If it returns False, pandas removes the entire group.
df_grouped.filter(func=filter_f)

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year
0,1,Paul Thomas,M,43,OH,M01-F0024,Desktop,479.99,143.39,Website,January,2018
1,2,Margo Simms,F,37,WV,GT13-0024,Desktop,1249.99,230.89,Flyer 4,January,2018
2,3,Sam Stine,M,26,PA,I3670,Desktop,649.99,118.64,Website,February,2018
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018
4,5,Jessica Elk,F,55,PA,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018
5,6,Sally Struthers,F,45,PA,GT13-0024,Desktop,1249.99,230.89,Flyer 2,April,2018
6,7,Michelle Samms,F,46,OH,GA401IV,Laptop,1349.99,180.34,Email,May,2018
8,9,Ed Klondike,M,52,OH,81TC00,Laptop,649.99,122.34,Email,July,2018
9,10,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,August,2018
10,11,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 3,November,2018
11,12,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,November,2018
12,13,Jason Case,M,57,PA,81TC00,Laptop,649.99,122.34,Email,November,2018
13,14,Doug Johnson,M,51,PA,I3670,Desktop,649.99,118.64,Website,December,2018
15,16,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,January,2019
16,17,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,February,2019
18,19,Mick Roberts,M,23,PA,I3593,Laptop,399.99,72.09,Flyer 4,March,2019
19,20,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2019
20,21,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,May,2019
21,22,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,August,2019
22,23,Paul Thomas,M,43,OH,81TC00,Laptop,649.99,122.34,Website,August,2019
23,24,Margo Simms,F,37,WV,Q526FA,Laptop,1049.99,143.09,Flyer 4,November,2019
24,25,Michelle Samms,F,46,NY,I3670,Desktop,649.99,118.64,Flyer 2,November,2019
25,26,Mick Roberts,M,23,PA,Q526FA,Laptop,1049.99,143.09,Email,November,2019
26,27,Ed Klondike,M,52,OH,Q526FA,Laptop,1049.99,143.09,Website,December,2019
27,28,Moe Eggert,M,35,PA,15M-ED,Laptop,699.99,98.09,Email,December,2019
28,29,Jessica Elk,F,55,PA,GA401IV,Laptop,1349.99,180.34,Flyer 2,December,2019
29,30,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,January,2020
30,31,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 1,January,2020
31,32,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,February,2020
32,33,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,March,2020
33,34,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,March,2020
35,36,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2020
36,37,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,April,2020
37,38,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,May,2020
38,39,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,May,2020

In [74]:
# Multiple filters vs groupby

jan_data = df[df['Month'] == 'January']
feb_data = df[df['Month'] == 'February']
dec_data = df[df['Month'] == 'December']

month_groups = df.groupby('Month') # Iterate only once!
jan_data2 = month_groups.get_group('January')
feb_data2 = month_groups.get_group('February')
dec_data2 = month_groups.get_group('December')

### apply (flexible)
https://pandas.pydata.org/pandas-docs/stable/user_guide/groupby.html#flexible-apply

In [75]:
display(df_grouped['Age'].apply(func=np.mean))

# Answer
def apply_f(group):
    return group.loc[group['Age'] >= 40]
df_grouped.apply(func=apply_f)

Product Type
Desktop    48.500000
Laptop     44.695652
Tablet     42.750000
Name: Age, dtype: float64

/var/folders/z4/cyv0pfhs0sb3531vj7glg5g00000gn/T/ipykernel_77650/452403619.py:6: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  df_grouped.apply(func=apply_f)

                 Sale ID          Contact Sex  Age State Product ID  \
Product Type
Desktop      0         1      Paul Thomas   M   43    OH  M01-F0024
             5         6  Sally Struthers   F   45    PA  GT13-0024
             9        10       Phil Jones   M   56    WV  M01-F0024
             11       12         Sue Etna   F   54    OH  GT13-0024
             13       14     Doug Johnson   M   51    PA      I3670
             20       21       Jason Case   M   57    PA  M01-F0024
             24       25   Michelle Samms   F   46    NY      I3670
             29       30       Phil Jones   M   56    WV  M01-F0024
             31       32         Sue Etna   F   54    OH  GT13-0024
             36       37       Jason Case   M   57    PA  M01-F0024
Laptop       4         5      Jessica Elk   F   55    PA     15M-ED
             6         7   Michelle Samms   F   46    OH    GA401IV
             8         9      Ed Klondike   M   52    OH     81TC00
             10       11       Rick James   M   49    PA    GA401IV
             12       13       Jason Case   M   57    PA     81TC00
             15       16      Kim Collins   F   49    PA      I3593
             16       17     Edna Sanders   F   46    OH     15M-ED
             19       20  Sally Struthers   F   45    NY     81TC00
             21       22     Doug Johnson   M   51    PA    GA401IV
             22       23      Paul Thomas   M   43    OH     81TC00
             26       27      Ed Klondike   M   52    OH     Q526FA
             28       29      Jessica Elk   F   55    PA    GA401IV
             30       31       Rick James   M   49    PA    GA401IV
             32       33      Kim Collins   F   49    PA      I3593
             33       34     Edna Sanders   F   46    OH     15M-ED
             35       36  Sally Struthers   F   45    NY     81TC00
             37       38     Doug Johnson   M   51    PA    GA401IV
Tablet       14       15       Andy Sands   M   56    OH    MY2J2LL
             17       18   Michelle Samms   F   46    NY    MY2J2LL
             34       35   Michelle Samms   F   46    NY    MY2J2LL

                Product Type  Sale Price  Profit     Lead     Month  Year
Product Type
Desktop      0       Desktop      479.99  143.39  Website   January  2018
             5       Desktop     1249.99  230.89  Flyer 2     April  2018
             9       Desktop      479.99  143.39  Flyer 2    August  2018
             11      Desktop     1249.99  230.89  Flyer 2  November  2018
             13      Desktop      649.99  118.64  Website  December  2018
             20      Desktop      479.99  143.39  Flyer 4       May  2019
             24      Desktop      649.99  118.64  Flyer 2  November  2019
             29      Desktop      479.99  143.39  Flyer 2   January  2020
             31      Desktop     1249.99  230.89  Flyer 2  February  2020
             36      Desktop      479.99  143.39  Flyer 4     April  2020
Laptop       4        Laptop      699.99   98.09  Flyer 4     March  2018
             6        Laptop     1349.99  180.34    Email       May  2018
             8        Laptop      649.99  122.34    Email      July  2018
             10       Laptop     1349.99  180.34  Flyer 3  November  2018
             12       Laptop      649.99  122.34    Email  November  2018
             15       Laptop      399.99   72.09  Flyer 2   January  2019
             16       Laptop      699.99   98.09    Email  February  2019
             19       Laptop      649.99  122.34  Website     April  2019
             21       Laptop     1349.99  180.34  Website    August  2019
             22       Laptop      649.99  122.34  Website    August  2019
             26       Laptop     1049.99  143.09  Website  December  2019
             28       Laptop     1349.99  180.34  Flyer 2  December  2019
             30       Laptop     1349.99  180.34  Flyer 1   January  2020
             32       Laptop      399.99   72.09  Flyer 2     March  2020
             33       Laptop      699.99   98.09    Email     March  2020
             35       Laptop      649.99  122.34  Website     April  2020
             37       Laptop     1349.99  180.34  Website       May  2020
Tablet       14       Tablet      999.99  146.69  Flyer 1  December  2018
             17       Tablet      999.99  146.69  Website     March  2019
             34       Tablet      999.99  146.69  Website     April  2020

In [76]:
# apply vs for-loop

sale_price_and_tax = []
for idx, item in df['Sale Price'].items():
    sale_price_and_tax.append(item * 1.10)
    
df['Sale Price With Tax'] = sale_price_and_tax
df['Sale Price With Tax2'] = df['Sale Price'].apply(lambda price: price * 1.1)

df

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year,Sale Price With Tax,Sale Price With Tax2
0,1,Paul Thomas,M,43,OH,M01-F0024,Desktop,479.99,143.39,Website,January,2018,527.989,527.989
1,2,Margo Simms,F,37,WV,GT13-0024,Desktop,1249.99,230.89,Flyer 4,January,2018,1374.989,1374.989
2,3,Sam Stine,M,26,PA,I3670,Desktop,649.99,118.64,Website,February,2018,714.989,714.989
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018,439.989,439.989
4,5,Jessica Elk,F,55,PA,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018,769.989,769.989
5,6,Sally Struthers,F,45,PA,GT13-0024,Desktop,1249.99,230.89,Flyer 2,April,2018,1374.989,1374.989
6,7,Michelle Samms,F,46,OH,GA401IV,Laptop,1349.99,180.34,Email,May,2018,1484.989,1484.989
7,8,Mick Roberts,M,23,OH,MY2J2LL,Tablet,999.99,146.69,Website,July,2018,1099.989,1099.989
8,9,Ed Klondike,M,52,OH,81TC00,Laptop,649.99,122.34,Email,July,2018,714.989,714.989
9,10,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,August,2018,527.989,527.989
10,11,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 3,November,2018,1484.989,1484.989
11,12,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,November,2018,1374.989,1374.989
12,13,Jason Case,M,57,PA,81TC00,Laptop,649.99,122.34,Email,November,2018,714.989,714.989
13,14,Doug Johnson,M,51,PA,I3670,Desktop,649.99,118.64,Website,December,2018,714.989,714.989
14,15,Andy Sands,M,56,OH,MY2J2LL,Tablet,999.99,146.69,Flyer 1,December,2018,1099.989,1099.989
15,16,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,January,2019,439.989,439.989
16,17,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,February,2019,769.989,769.989
17,18,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,March,2019,1099.989,1099.989
18,19,Mick Roberts,M,23,PA,I3593,Laptop,399.99,72.09,Flyer 4,March,2019,439.989,439.989
19,20,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2019,714.989,714.989
20,21,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,May,2019,527.989,527.989
21,22,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,August,2019,1484.989,1484.989
22,23,Paul Thomas,M,43,OH,81TC00,Laptop,649.99,122.34,Website,August,2019,714.989,714.989
23,24,Margo Simms,F,37,WV,Q526FA,Laptop,1049.99,143.09,Flyer 4,November,2019,1154.989,1154.989
24,25,Michelle Samms,F,46,NY,I3670,Desktop,649.99,118.64,Flyer 2,November,2019,714.989,714.989
25,26,Mick Roberts,M,23,PA,Q526FA,Laptop,1049.99,143.09,Email,November,2019,1154.989,1154.989
26,27,Ed Klondike,M,52,OH,Q526FA,Laptop,1049.99,143.09,Website,December,2019,1154.989,1154.989
27,28,Moe Eggert,M,35,PA,15M-ED,Laptop,699.99,98.09,Email,December,2019,769.989,769.989
28,29,Jessica Elk,F,55,PA,GA401IV,Laptop,1349.99,180.34,Flyer 2,December,2019,1484.989,1484.989
29,30,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,January,2020,527.989,527.989
30,31,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 1,January,2020,1484.989,1484.989
31,32,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,February,2020,1374.989,1374.989
32,33,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,March,2020,439.989,439.989
33,34,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,March,2020,769.989,769.989
34,35,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,April,2020,1099.989,1099.989
35,36,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2020,714.989,714.989
36,37,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,April,2020,527.989,527.989
37,38,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,May,2020,1484.989,1484.989
38,39,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,May,2020,439.989,439.989

## Concatenate, Merge, Join
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html
https://realpython.com/pandas-merge-join-and-concat/
https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html#merge-join-concatenate-and-compare

### Concatenate

In [77]:
d1 = df.loc[:3]
d2 = df.loc[3:]
display(d1)
display(d2)

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year,Sale Price With Tax,Sale Price With Tax2
0,1,Paul Thomas,M,43,OH,M01-F0024,Desktop,479.99,143.39,Website,January,2018,527.989,527.989
1,2,Margo Simms,F,37,WV,GT13-0024,Desktop,1249.99,230.89,Flyer 4,January,2018,1374.989,1374.989
2,3,Sam Stine,M,26,PA,I3670,Desktop,649.99,118.64,Website,February,2018,714.989,714.989
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018,439.989,439.989

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year,Sale Price With Tax,Sale Price With Tax2
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018,439.989,439.989
4,5,Jessica Elk,F,55,PA,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018,769.989,769.989
5,6,Sally Struthers,F,45,PA,GT13-0024,Desktop,1249.99,230.89,Flyer 2,April,2018,1374.989,1374.989
6,7,Michelle Samms,F,46,OH,GA401IV,Laptop,1349.99,180.34,Email,May,2018,1484.989,1484.989
7,8,Mick Roberts,M,23,OH,MY2J2LL,Tablet,999.99,146.69,Website,July,2018,1099.989,1099.989
8,9,Ed Klondike,M,52,OH,81TC00,Laptop,649.99,122.34,Email,July,2018,714.989,714.989
9,10,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,August,2018,527.989,527.989
10,11,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 3,November,2018,1484.989,1484.989
11,12,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,November,2018,1374.989,1374.989
12,13,Jason Case,M,57,PA,81TC00,Laptop,649.99,122.34,Email,November,2018,714.989,714.989
13,14,Doug Johnson,M,51,PA,I3670,Desktop,649.99,118.64,Website,December,2018,714.989,714.989
14,15,Andy Sands,M,56,OH,MY2J2LL,Tablet,999.99,146.69,Flyer 1,December,2018,1099.989,1099.989
15,16,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,January,2019,439.989,439.989
16,17,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,February,2019,769.989,769.989
17,18,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,March,2019,1099.989,1099.989
18,19,Mick Roberts,M,23,PA,I3593,Laptop,399.99,72.09,Flyer 4,March,2019,439.989,439.989
19,20,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2019,714.989,714.989
20,21,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,May,2019,527.989,527.989
21,22,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,August,2019,1484.989,1484.989
22,23,Paul Thomas,M,43,OH,81TC00,Laptop,649.99,122.34,Website,August,2019,714.989,714.989
23,24,Margo Simms,F,37,WV,Q526FA,Laptop,1049.99,143.09,Flyer 4,November,2019,1154.989,1154.989
24,25,Michelle Samms,F,46,NY,I3670,Desktop,649.99,118.64,Flyer 2,November,2019,714.989,714.989
25,26,Mick Roberts,M,23,PA,Q526FA,Laptop,1049.99,143.09,Email,November,2019,1154.989,1154.989
26,27,Ed Klondike,M,52,OH,Q526FA,Laptop,1049.99,143.09,Website,December,2019,1154.989,1154.989
27,28,Moe Eggert,M,35,PA,15M-ED,Laptop,699.99,98.09,Email,December,2019,769.989,769.989
28,29,Jessica Elk,F,55,PA,GA401IV,Laptop,1349.99,180.34,Flyer 2,December,2019,1484.989,1484.989
29,30,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,January,2020,527.989,527.989
30,31,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 1,January,2020,1484.989,1484.989
31,32,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,February,2020,1374.989,1374.989
32,33,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,March,2020,439.989,439.989
33,34,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,March,2020,769.989,769.989
34,35,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,April,2020,1099.989,1099.989
35,36,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2020,714.989,714.989
36,37,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,April,2020,527.989,527.989
37,38,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,May,2020,1484.989,1484.989
38,39,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,May,2020,439.989,439.989

In [78]:
pd.concat([d1, d2], axis=0)
# With axis=0, pandas stacks the DataFrames vertically, so we're adding rows.

,Sale ID,Contact,Sex,Age,State,Product ID,Product Type,Sale Price,Profit,Lead,Month,Year,Sale Price With Tax,Sale Price With Tax2
0,1,Paul Thomas,M,43,OH,M01-F0024,Desktop,479.99,143.39,Website,January,2018,527.989,527.989
1,2,Margo Simms,F,37,WV,GT13-0024,Desktop,1249.99,230.89,Flyer 4,January,2018,1374.989,1374.989
2,3,Sam Stine,M,26,PA,I3670,Desktop,649.99,118.64,Website,February,2018,714.989,714.989
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018,439.989,439.989
3,4,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,March,2018,439.989,439.989
4,5,Jessica Elk,F,55,PA,15M-ED,Laptop,699.99,98.09,Flyer 4,March,2018,769.989,769.989
5,6,Sally Struthers,F,45,PA,GT13-0024,Desktop,1249.99,230.89,Flyer 2,April,2018,1374.989,1374.989
6,7,Michelle Samms,F,46,OH,GA401IV,Laptop,1349.99,180.34,Email,May,2018,1484.989,1484.989
7,8,Mick Roberts,M,23,OH,MY2J2LL,Tablet,999.99,146.69,Website,July,2018,1099.989,1099.989
8,9,Ed Klondike,M,52,OH,81TC00,Laptop,649.99,122.34,Email,July,2018,714.989,714.989
9,10,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,August,2018,527.989,527.989
10,11,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 3,November,2018,1484.989,1484.989
11,12,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,November,2018,1374.989,1374.989
12,13,Jason Case,M,57,PA,81TC00,Laptop,649.99,122.34,Email,November,2018,714.989,714.989
13,14,Doug Johnson,M,51,PA,I3670,Desktop,649.99,118.64,Website,December,2018,714.989,714.989
14,15,Andy Sands,M,56,OH,MY2J2LL,Tablet,999.99,146.69,Flyer 1,December,2018,1099.989,1099.989
15,16,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,January,2019,439.989,439.989
16,17,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,February,2019,769.989,769.989
17,18,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,March,2019,1099.989,1099.989
18,19,Mick Roberts,M,23,PA,I3593,Laptop,399.99,72.09,Flyer 4,March,2019,439.989,439.989
19,20,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2019,714.989,714.989
20,21,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,May,2019,527.989,527.989
21,22,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,August,2019,1484.989,1484.989
22,23,Paul Thomas,M,43,OH,81TC00,Laptop,649.99,122.34,Website,August,2019,714.989,714.989
23,24,Margo Simms,F,37,WV,Q526FA,Laptop,1049.99,143.09,Flyer 4,November,2019,1154.989,1154.989
24,25,Michelle Samms,F,46,NY,I3670,Desktop,649.99,118.64,Flyer 2,November,2019,714.989,714.989
25,26,Mick Roberts,M,23,PA,Q526FA,Laptop,1049.99,143.09,Email,November,2019,1154.989,1154.989
26,27,Ed Klondike,M,52,OH,Q526FA,Laptop,1049.99,143.09,Website,December,2019,1154.989,1154.989
27,28,Moe Eggert,M,35,PA,15M-ED,Laptop,699.99,98.09,Email,December,2019,769.989,769.989
28,29,Jessica Elk,F,55,PA,GA401IV,Laptop,1349.99,180.34,Flyer 2,December,2019,1484.989,1484.989
29,30,Phil Jones,M,56,WV,M01-F0024,Desktop,479.99,143.39,Flyer 2,January,2020,527.989,527.989
30,31,Rick James,M,49,PA,GA401IV,Laptop,1349.99,180.34,Flyer 1,January,2020,1484.989,1484.989
31,32,Sue Etna,F,54,OH,GT13-0024,Desktop,1249.99,230.89,Flyer 2,February,2020,1374.989,1374.989
32,33,Kim Collins,F,49,PA,I3593,Laptop,399.99,72.09,Flyer 2,March,2020,439.989,439.989
33,34,Edna Sanders,F,46,OH,15M-ED,Laptop,699.99,98.09,Email,March,2020,769.989,769.989
34,35,Michelle Samms,F,46,NY,MY2J2LL,Tablet,999.99,146.69,Website,April,2020,1099.989,1099.989
35,36,Sally Struthers,F,45,NY,81TC00,Laptop,649.99,122.34,Website,April,2020,714.989,714.989
36,37,Jason Case,M,57,PA,M01-F0024,Desktop,479.99,143.39,Flyer 4,April,2020,527.989,527.989
37,38,Doug Johnson,M,51,PA,GA401IV,Laptop,1349.99,180.34,Website,May,2020,1484.989,1484.989
38,39,Moe Eggert,M,35,PA,I3593,Laptop,399.99,72.09,Website,May,2020,439.989,439.989

In [79]:
left = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                      'B': ['B0', 'B1', 'B2']},
                     index=['K0', 'K1', 'K2'])
right = pd.DataFrame({'C': ['C0', 'C2', 'C3'],
                       'D': ['D0', 'D2', 'D3']},
                      index=['K0', 'K2', 'K3'])
display(left)
display(right)
left.join(right)
# join aligns the two DataFrames using their indices.

     A   B
K0  A0  B0
K1  A1  B1
K2  A2  B2

     C   D
K0  C0  D0
K2  C2  D2
K3  C3  D3

     A   B    C    D
K0  A0  B0   C0   D0
K1  A1  B1  NaN  NaN
K2  A2  B2   C2   D2

### merge

In [88]:
d1 = df.loc[:3, ['Contact', 'Age', 'Product ID']]
d2 = df.loc[3:, ['Contact', 'Age', 'Product ID']]
display(d1)
display(d2)

       Contact  Age Product ID
0  Paul Thomas   43  M01-F0024
1  Margo Simms   37  GT13-0024
2    Sam Stine   26      I3670
3   Moe Eggert   35      I3593

            Contact  Age Product ID
3        Moe Eggert   35      I3593
4       Jessica Elk   55     15M-ED
5   Sally Struthers   45  GT13-0024
6    Michelle Samms   46    GA401IV
7      Mick Roberts   23    MY2J2LL
8       Ed Klondike   52     81TC00
9        Phil Jones   56  M01-F0024
10       Rick James   49    GA401IV
11         Sue Etna   54  GT13-0024
12       Jason Case   57     81TC00
13     Doug Johnson   51      I3670
14       Andy Sands   56    MY2J2LL
15      Kim Collins   49      I3593
16     Edna Sanders   46     15M-ED
17   Michelle Samms   46    MY2J2LL
18     Mick Roberts   23      I3593
19  Sally Struthers   45     81TC00
20       Jason Case   57  M01-F0024
21     Doug Johnson   51    GA401IV
22      Paul Thomas   43     81TC00
23      Margo Simms   37     Q526FA
24   Michelle Samms   46      I3670
25     Mick Roberts   23     Q526FA
26      Ed Klondike   52     Q526FA
27       Moe Eggert   35     15M-ED
28      Jessica Elk   55    GA401IV
29       Phil Jones   56  M01-F0024
30       Rick James   49    GA401IV
31         Sue Etna   54  GT13-0024
32      Kim Collins   49      I3593
33     Edna Sanders   46     15M-ED
34   Michelle Samms   46    MY2J2LL
35  Sally Struthers   45     81TC00
36       Jason Case   57  M01-F0024
37     Doug Johnson   51    GA401IV
38       Moe Eggert   35      I3593

In [81]:
# We're merging the two DataFrames using Contact as the key.
merged_df = d1.merge(right=d2, how='left', on="Contact")
merged_df
# The left table decides which keys must stay.
# Pandas looks for a matching Contact value on the right.
# If it finds one, the values are combined.
# If it doesn't find one, the columns coming from the right side contain NaN.

       Contact  Age_x Product ID_x  Age_y Product ID_y
0  Paul Thomas     43    M01-F0024   43.0       81TC00
1  Margo Simms     37    GT13-0024   37.0       Q526FA
2    Sam Stine     26        I3670    NaN          NaN
3   Moe Eggert     35        I3593   35.0        I3593
4   Moe Eggert     35        I3593   35.0       15M-ED
5   Moe Eggert     35        I3593   35.0        I3593

In [82]:
merged_df = d1.merge(right=d2, how='right', on="Contact")
merged_df

            Contact  Age_x Product ID_x  Age_y Product ID_y
0        Moe Eggert   35.0        I3593     35        I3593
1       Jessica Elk    NaN          NaN     55       15M-ED
2   Sally Struthers    NaN          NaN     45    GT13-0024
3    Michelle Samms    NaN          NaN     46      GA401IV
4      Mick Roberts    NaN          NaN     23      MY2J2LL
5       Ed Klondike    NaN          NaN     52       81TC00
6        Phil Jones    NaN          NaN     56    M01-F0024
7        Rick James    NaN          NaN     49      GA401IV
8          Sue Etna    NaN          NaN     54    GT13-0024
9        Jason Case    NaN          NaN     57       81TC00
10     Doug Johnson    NaN          NaN     51        I3670
11       Andy Sands    NaN          NaN     56      MY2J2LL
12      Kim Collins    NaN          NaN     49        I3593
13     Edna Sanders    NaN          NaN     46       15M-ED
14   Michelle Samms    NaN          NaN     46      MY2J2LL
15     Mick Roberts    NaN          NaN     23        I3593
16  Sally Struthers    NaN          NaN     45       81TC00
17       Jason Case    NaN          NaN     57    M01-F0024
18     Doug Johnson    NaN          NaN     51      GA401IV
19      Paul Thomas   43.0    M01-F0024     43       81TC00
20      Margo Simms   37.0    GT13-0024     37       Q526FA
21   Michelle Samms    NaN          NaN     46        I3670
22     Mick Roberts    NaN          NaN     23       Q526FA
23      Ed Klondike    NaN          NaN     52       Q526FA
24       Moe Eggert   35.0        I3593     35       15M-ED
25      Jessica Elk    NaN          NaN     55      GA401IV
26       Phil Jones    NaN          NaN     56    M01-F0024
27       Rick James    NaN          NaN     49      GA401IV
28         Sue Etna    NaN          NaN     54    GT13-0024
29      Kim Collins    NaN          NaN     49        I3593
30     Edna Sanders    NaN          NaN     46       15M-ED
31   Michelle Samms    NaN          NaN     46      MY2J2LL
32  Sally Struthers    NaN          NaN     45       81TC00
33       Jason Case    NaN          NaN     57    M01-F0024
34     Doug Johnson    NaN          NaN     51      GA401IV
35       Moe Eggert   35.0        I3593     35        I3593

In [83]:
merged_df = d1.merge(right=d2, how='inner', on="Contact")
merged_df
# An inner merge keeps only keys that appear in both DataFrames.

       Contact  Age_x Product ID_x  Age_y Product ID_y
0  Paul Thomas     43    M01-F0024     43       81TC00
1  Margo Simms     37    GT13-0024     37       Q526FA
2   Moe Eggert     35        I3593     35        I3593
3   Moe Eggert     35        I3593     35       15M-ED
4   Moe Eggert     35        I3593     35        I3593

In [84]:
merged_df = d1.merge(right=d2, how='outer', on="Contact")
merged_df
#An outer merge keeps all keys from both DataFrames.

            Contact  Age_x Product ID_x  Age_y Product ID_y
0        Andy Sands    NaN          NaN   56.0      MY2J2LL
1      Doug Johnson    NaN          NaN   51.0        I3670
2      Doug Johnson    NaN          NaN   51.0      GA401IV
3      Doug Johnson    NaN          NaN   51.0      GA401IV
4       Ed Klondike    NaN          NaN   52.0       81TC00
5       Ed Klondike    NaN          NaN   52.0       Q526FA
6      Edna Sanders    NaN          NaN   46.0       15M-ED
7      Edna Sanders    NaN          NaN   46.0       15M-ED
8        Jason Case    NaN          NaN   57.0       81TC00
9        Jason Case    NaN          NaN   57.0    M01-F0024
10       Jason Case    NaN          NaN   57.0    M01-F0024
11      Jessica Elk    NaN          NaN   55.0       15M-ED
12      Jessica Elk    NaN          NaN   55.0      GA401IV
13      Kim Collins    NaN          NaN   49.0        I3593
14      Kim Collins    NaN          NaN   49.0        I3593
15      Margo Simms   37.0    GT13-0024   37.0       Q526FA
16   Michelle Samms    NaN          NaN   46.0      GA401IV
17   Michelle Samms    NaN          NaN   46.0      MY2J2LL
18   Michelle Samms    NaN          NaN   46.0        I3670
19   Michelle Samms    NaN          NaN   46.0      MY2J2LL
20     Mick Roberts    NaN          NaN   23.0      MY2J2LL
21     Mick Roberts    NaN          NaN   23.0        I3593
22     Mick Roberts    NaN          NaN   23.0       Q526FA
23       Moe Eggert   35.0        I3593   35.0        I3593
24       Moe Eggert   35.0        I3593   35.0       15M-ED
25       Moe Eggert   35.0        I3593   35.0        I3593
26      Paul Thomas   43.0    M01-F0024   43.0       81TC00
27       Phil Jones    NaN          NaN   56.0    M01-F0024
28       Phil Jones    NaN          NaN   56.0    M01-F0024
29       Rick James    NaN          NaN   49.0      GA401IV
30       Rick James    NaN          NaN   49.0      GA401IV
31  Sally Struthers    NaN          NaN   45.0    GT13-0024
32  Sally Struthers    NaN          NaN   45.0       81TC00
33  Sally Struthers    NaN          NaN   45.0       81TC00
34        Sam Stine   26.0        I3670    NaN          NaN
35         Sue Etna    NaN          NaN   54.0    GT13-0024
36         Sue Etna    NaN          NaN   54.0    GT13-0024

In [85]:
merged_df = d1.merge(right=d2, how='outer', on=["Contact", "Product ID"])
merged_df
# The pair of columns together acts as the key.

            Contact  Age_x Product ID  Age_y
0        Andy Sands    NaN    MY2J2LL   56.0
1      Doug Johnson    NaN    GA401IV   51.0
2      Doug Johnson    NaN    GA401IV   51.0
3      Doug Johnson    NaN      I3670   51.0
4       Ed Klondike    NaN     81TC00   52.0
5       Ed Klondike    NaN     Q526FA   52.0
6      Edna Sanders    NaN     15M-ED   46.0
7      Edna Sanders    NaN     15M-ED   46.0
8        Jason Case    NaN     81TC00   57.0
9        Jason Case    NaN  M01-F0024   57.0
10       Jason Case    NaN  M01-F0024   57.0
11      Jessica Elk    NaN     15M-ED   55.0
12      Jessica Elk    NaN    GA401IV   55.0
13      Kim Collins    NaN      I3593   49.0
14      Kim Collins    NaN      I3593   49.0
15      Margo Simms   37.0  GT13-0024    NaN
16      Margo Simms    NaN     Q526FA   37.0
17   Michelle Samms    NaN    GA401IV   46.0
18   Michelle Samms    NaN      I3670   46.0
19   Michelle Samms    NaN    MY2J2LL   46.0
20   Michelle Samms    NaN    MY2J2LL   46.0
21     Mick Roberts    NaN      I3593   23.0
22     Mick Roberts    NaN    MY2J2LL   23.0
23     Mick Roberts    NaN     Q526FA   23.0
24       Moe Eggert    NaN     15M-ED   35.0
25       Moe Eggert   35.0      I3593   35.0
26       Moe Eggert   35.0      I3593   35.0
27      Paul Thomas    NaN     81TC00   43.0
28      Paul Thomas   43.0  M01-F0024    NaN
29       Phil Jones    NaN  M01-F0024   56.0
30       Phil Jones    NaN  M01-F0024   56.0
31       Rick James    NaN    GA401IV   49.0
32       Rick James    NaN    GA401IV   49.0
33  Sally Struthers    NaN     81TC00   45.0
34  Sally Struthers    NaN     81TC00   45.0
35  Sally Struthers    NaN  GT13-0024   45.0
36        Sam Stine   26.0      I3670    NaN
37         Sue Etna    NaN  GT13-0024   54.0
38         Sue Etna    NaN  GT13-0024   54.0

## Group Practice

Work in groups of **2–3 students**.



Merge the two DataFrames on `StudentID` using: `inner`, `left`, `outer`

Before running the code, **predict the result**.

For each merge, check:

- How many rows are there?
- Which `StudentID`s remain?
- Where do `NaN` values appear?

In [86]:
students = pd.DataFrame({
    'StudentID': [1, 2, 3],
    'Name': ['Ana', 'Ben', 'Chen']
})

scores = pd.DataFrame({
    'StudentID': [2, 3, 4],
    'Score': [88, 92, 75]
})

In [87]:
inner_result = students.merge(scores, on='StudentID', how='inner')
left_result = students.merge(scores, on='StudentID', how='left')
outer_result = students.merge(scores, on='StudentID', how='outer')

display(inner_result, left_result, outer_result)

   StudentID  Name  Score
0          2   Ben     88
1          3  Chen     92

   StudentID  Name  Score
0          1   Ana    NaN
1          2   Ben   88.0
2          3  Chen   92.0

   StudentID  Name  Score
0          1   Ana    NaN
1          2   Ben   88.0
2          3  Chen   92.0
3          4   NaN   75.0